#!/bin/bash

php app/console doctrine:database:drop --force
php app/console doctrine:database:create
php app/console doctrine:schema:update --force
XDEBUG_CONFIG="idekey=PHPSTORM" php app/console doctrine:fixtures:load --no-interaction
