parameters:
#    night_display.example.class: Night\DisplayBundle\Example

services:
#    night_display.example:
#        class: %night_display.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
